"""Aggregate the multi-seed credit-card runs into one summary table.

Reads every results/experiment_creditcard_real*.csv (base seed 42 plus
_seed<N> variants) and the matching *_diffs.csv files, and writes
results/seed_summary_creditcard.{csv,md}: per-model mean +/- sd (and
min-max) of AUC and AP over the seeds, plus the per-seed paired
ablation difference (learned - no-context) and how many seeds' paired
95% CI excludes zero, for AUC and AP separately.

Regenerate, never hand-edit. Deterministic given the input files.
"""

import csv
import math
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"

MODELS = ["logistic_regression", "ebm_interpretml", "gradient_boosting_balanced",
          "rulefit", "pla_static", "pla_learned", "pla_learned_noctx"]


def _seed_of(path):
    match = re.search(r"_seed(\d+)\.csv$", path.name)
    return int(match.group(1)) if match else 42


def _mean_sd(values):
    mean = sum(values) / len(values)
    if len(values) < 2:
        return mean, 0.0
    var = sum((v - mean) ** 2 for v in values) / (len(values) - 1)
    return mean, math.sqrt(var)


def main():
    experiment_files = sorted(
        (p for p in RESULTS.glob("experiment_creditcard_real*.csv")
         if not p.name.endswith("_diffs.csv")),
        key=_seed_of)
    seeds = [_seed_of(p) for p in experiment_files]

    per_model = {m: {"auc": [], "ap": []} for m in MODELS}
    for path in experiment_files:
        with open(path, newline="") as handle:
            for row in csv.DictReader(handle):
                if row["model"] in per_model and row["auc"] != "":
                    per_model[row["model"]]["auc"].append(float(row["auc"]))
                    per_model[row["model"]]["ap"].append(float(row["ap"]))

    diffs = []
    for path in experiment_files:
        diff_path = path.with_name(path.stem + "_diffs.csv")
        if not diff_path.exists():
            continue
        with open(diff_path, newline="") as handle:
            for row in csv.DictReader(handle):
                if row["contrast"] == "pla_learned_minus_noctx":
                    diffs.append({"seed": _seed_of(path), **row})

    out_rows = []
    for model in MODELS:
        aucs, aps = per_model[model]["auc"], per_model[model]["ap"]
        if not aucs:
            continue
        auc_mean, auc_sd = _mean_sd(aucs)
        ap_mean, ap_sd = _mean_sd(aps)
        out_rows.append({
            "model": model, "n_seeds": len(aucs),
            "auc_mean": f"{auc_mean:.4f}", "auc_sd": f"{auc_sd:.4f}",
            "auc_min": f"{min(aucs):.4f}", "auc_max": f"{max(aucs):.4f}",
            "ap_mean": f"{ap_mean:.4f}", "ap_sd": f"{ap_sd:.4f}",
            "ap_min": f"{min(aps):.4f}", "ap_max": f"{max(aps):.4f}",
        })

    csv_path = RESULTS / "seed_summary_creditcard.csv"
    with open(csv_path, "w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(out_rows[0]))
        writer.writeheader()
        writer.writerows(out_rows)

    auc_excl = sum(1 for d in diffs
                   if float(d["auc_diff_lo"]) > 0 or float(d["auc_diff_hi"]) < 0)
    ap_excl = sum(1 for d in diffs
                  if float(d["ap_diff_lo"]) > 0 or float(d["ap_diff_hi"]) < 0)

    lines = [
        "# Multi-seed summary: credit card",
        "",
        "Generated by `python scripts/make_seed_summary.py` — do not edit by hand.",
        f"Seeds: {', '.join(map(str, seeds))} ({len(seeds)} random 70/30 splits;",
        "seeds beyond 42–44 run with `--fast`, which skips only the ProbLog and",
        "pgmpy cross-check rows).",
        "",
        "| Model | AUC mean ± sd | AUC min–max | AP mean ± sd | AP min–max |",
        "|---|---|---|---|---|",
    ]
    for row in out_rows:
        lines.append(
            f"| {row['model']} | {row['auc_mean']} ± {row['auc_sd']} "
            f"| {row['auc_min']}–{row['auc_max']} "
            f"| {row['ap_mean']} ± {row['ap_sd']} "
            f"| {row['ap_min']}–{row['ap_max']} |")

    lines += [
        "",
        "Per-seed paired ablation difference (pla_learned − pla_learned_noctx),",
        "paired bootstrap 95% CIs:",
        "",
        "| Seed | ΔAUC [95% CI] | ΔAP [95% CI] |",
        "|---|---|---|",
    ]
    for d in sorted(diffs, key=lambda d: d["seed"]):
        lines.append(
            f"| {d['seed']} | {d['auc_diff']} [{d['auc_diff_lo']}, {d['auc_diff_hi']}] "
            f"| {d['ap_diff']} [{d['ap_diff_lo']}, {d['ap_diff_hi']}] |")
    lines += [
        "",
        f"Seeds whose paired 95% CI excludes zero — ΔAUC: {auc_excl}/{len(diffs)}; "
        f"ΔAP: {ap_excl}/{len(diffs)}.",
    ]
    md_path = RESULTS / "seed_summary_creditcard.md"
    md_path.write_text("\n".join(lines) + "\n")
    print(f"written: {csv_path} and {md_path}")


if __name__ == "__main__":
    main()
