"""Generate the paper's case study: one real fraud's trace, end to end.

Deterministically selects the highest-static-scored TRUE POSITIVE in the
credit-card test split, then reports: the fired rules with their empirical
precisions, the noisy-OR fold arithmetic, the learned model's score, the
engine's own explanation trace, and the deletion counterfactual (remove
the top rule's facts; the score drops accordingly).

Writes results/case_study_creditcard.md. Regenerate, never hand-edit.

Usage:
    python scripts/make_case_study.py --data data/creditcard.csv
"""

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

import run_baselines as rb  # noqa: E402

from pla.learn import RuleWeightLearner  # noqa: E402
from pla.pipeline import (  # noqa: E402
    CREDITCARD,
    build_examples,
    fit_discretizer,
    generate_rule_specs,
    load_rows,
    noisy_or_probability,
)
from pla.prob import ProbKB, ProbRule, ProbSymbol  # noqa: E402

RESULTS_DIR = ROOT / "results"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", default="data/creditcard.csv")
    args = parser.parse_args()

    rows = rb.parseable_rows(load_rows(args.data), CREDITCARD)
    train_rows, test_rows = rb.split_rows(rows)
    thresholds = fit_discretizer(train_rows, schema=CREDITCARD)
    train_examples = build_examples(train_rows, thresholds, schema=CREDITCARD)
    test_examples = build_examples(test_rows, thresholds, schema=CREDITCARD)
    specs, precisions = generate_rule_specs(
        train_examples, context_vars=CREDITCARD.all_context_vars
    )

    learner = RuleWeightLearner(specs, use_bias=True)
    learner.fit(train_examples, epochs=400, learning_rate=1.0)

    # Deterministic pick: highest static score among true positives.
    best = max(
        (e for e in test_examples if e[2] == 1),
        key=lambda e: (noisy_or_probability(specs, precisions, e[0]), sorted(e[0])),
    )
    facts, context, _ = best

    fired = [
        (spec, precision)
        for spec, precision in zip(specs, precisions)
        if all(a in facts for a in spec.antecedents)
    ]
    fired.sort(key=lambda item: -item[1])

    static_score = noisy_or_probability(specs, precisions, facts)
    learned_score = learner.predict_proba(facts, context)

    # Deletion counterfactual: remove the top rule's antecedent facts.
    top_spec = fired[0][0]
    reduced = frozenset(facts - set(top_spec.antecedents))
    static_after = noisy_or_probability(specs, precisions, reduced)
    learned_after = learner.predict_proba(reduced, context)

    # Leave-one-rule-out: each fired rule removed from the fold alone,
    # facts untouched — the per-rule contribution without the
    # overlapping-antecedent confound of fact deletion. For the learned
    # model the log-odds drop equals z_r exactly (additive path).
    import math

    def logit(p, eps=1e-9):
        p = min(max(p, eps), 1 - eps)
        return math.log(p / (1 - p))

    fired_indices = [i for i, spec in enumerate(specs)
                     if all(a in facts for a in spec.antecedents)]
    loro_lines = []
    for i in sorted(fired_indices,
                    key=lambda j: -precisions[j]):
        static_wo = 0.0
        for j in fired_indices:
            if j != i:
                static_wo = 1 - (1 - static_wo) * (1 - precisions[j])
        z_wo = sum(learner._z(j, context) for j in fired_indices if j != i)
        learned_wo = 1 / (1 + math.exp(-(learner.bias + z_wo)))
        loro_lines.append(
            f"| {' ∧ '.join(specs[i].antecedents)} "
            f"| {static_score - static_wo:.4f} "
            f"| {learned_score - learned_wo:.4f} "
            f"| {logit(learned_score) - logit(learned_wo):.4f} "
            f"| {learner._z(i, context):.4f} |"
        )

    # The engine's own trace for the same example.
    kb = ProbKB()  # default noisy_or, legacy context (neutral weights)
    head = ProbSymbol("Fraud")
    for spec, precision in zip(specs, precisions):
        kb.add_rule(ProbRule([ProbSymbol(a) for a in spec.antecedents], head, precision))
    for fact in sorted(facts):
        kb.add_fact(fact)
    engine_prob, engine_trace = kb.query("Fraud")

    fold = 0.0
    fold_lines = []
    for spec, precision in fired:
        new = 1 - (1 - fold) * (1 - precision)
        fold_lines.append(
            f"| {' ∧ '.join(spec.antecedents)} | {precision:.4f} | "
            f"1−(1−{fold:.4f})(1−{precision:.4f}) = {new:.4f} |"
        )
        fold = new

    lines = [
        "# Case study: one real fraud, traced end to end",
        "",
        "Generated by `python scripts/make_case_study.py` — do not edit by hand.",
        "Example: the highest-static-scored true positive in the credit-card",
        "test split (split seed 42). Facts are quantile propositions of the",
        "transaction's features; every probability below is an empirical",
        "training-set precision.",
        "",
        f"**Active propositions ({len(facts)}):** " + ", ".join(sorted(facts)),
        f"**Active context:** {', '.join(sorted(context)) or '(none)'}",
        "",
        f"## Fired rules ({len(fired)} of {len(specs)}) and the noisy-OR fold",
        "",
        "| Rule | Empirical precision | Running noisy-OR |",
        "|---|---|---|",
        *fold_lines,
        "",
        f"**PLA static score: {static_score:.4f}** (true label: fraud).",
        f"**PLA learned score: {learned_score:.4f}** (logit path + bias).",
        "",
        "## Deletion counterfactual",
        "",
        f"Removing the top rule's facts ({' ∧ '.join(top_spec.antecedents)}):",
        f"static {static_score:.4f} → {static_after:.4f}; "
        f"learned {learned_score:.4f} → {learned_after:.4f}.",
        "The trace's top factor is load-bearing, not decorative.",
        "",
        "## Leave-one-rule-out contributions",
        "",
        "Each fired rule removed from the fold alone (facts untouched).",
        "For the learned model, Δlog-odds equals the rule's z_r exactly —",
        "the trace ranking is the exact attribution on that scale.",
        "",
        "| Rule | Δ static | Δ learned | Δ learned log-odds | z_r |",
        "|---|---|---|---|---|",
        *loro_lines,
        "",
        "## The engine's own trace (verbatim)",
        "",
        "```",
        f"query(Fraud) = {engine_prob:.6f}",
        engine_trace,
        "```",
    ]

    RESULTS_DIR.mkdir(exist_ok=True)
    out = RESULTS_DIR / "case_study_creditcard.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"written: {out}")
    print(f"static {static_score:.4f} -> {static_after:.4f} | "
          f"learned {learned_score:.4f} -> {learned_after:.4f} | fired {len(fired)}")


if __name__ == "__main__":
    main()
