"""E5: explanation-fidelity report for the E4 PLA models.

For pla_static and pla_learned, computes trace-fidelity metrics
(comprehensiveness up, sufficiency near zero — see pla/fidelity.py) plus a
reversed-attribution control per model showing the metric discriminates
faithful rankings from deliberately wrong ones.

Deterministic like E4; writes results/fidelity_<tag>.csv and .md.

Usage:
    python scripts/run_fidelity.py --synthetic 2000 --seed 0
    python scripts/run_fidelity.py --data data/creditcard.csv --tag real
"""

import argparse
import csv
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

import fetch_fraud_data as ffd  # noqa: E402
import run_baselines as rb  # noqa: E402
import run_experiments as rx  # noqa: E402

from pla.fidelity import (  # noqa: E402
    evaluate_fidelity,
    learned_attributions,
    reversed_attributions,
    static_attributions,
)
from pla.learn import RuleWeightLearner  # noqa: E402
from pla.pipeline import (  # noqa: E402
    CREDITCARD,
    SCHEMAS,
    build_examples,
    fit_discretizer,
    generate_rule_specs,
    load_rows,
    noisy_or_probability,
)

RESULTS_DIR = ROOT / "results"


def run(data_path, tag, schema=CREDITCARD, temporal=None):
    rows = rb.parseable_rows(load_rows(data_path), schema)
    if temporal:
        column, train_end, test_start = temporal
        train_rows, test_rows = rx.split_rows_temporal(rows, column, train_end, test_start)
    else:
        train_rows, test_rows = rb.split_rows(rows)
    if schema.label == "misstate":
        train_rows, _ = rx.drop_post_first_fraud(train_rows)
    thresholds = fit_discretizer(train_rows, schema=schema)
    train_examples = build_examples(train_rows, thresholds, schema=schema)
    test_examples = build_examples(test_rows, thresholds, schema=schema)
    context_vars = schema.all_context_vars
    rule_specs, precisions = generate_rule_specs(train_examples, context_vars=context_vars)

    learner = RuleWeightLearner(rule_specs, use_bias=True)
    learner.fit(train_examples, epochs=400, learning_rate=1.0)

    def static_predict(facts, _context):
        return noisy_or_probability(rule_specs, precisions, facts)

    def learned_predict(facts, context):
        return learner.predict_proba(facts, context)

    models = [
        ("pla_static", static_predict, static_attributions(rule_specs, precisions)),
        ("pla_learned", learned_predict, learned_attributions(learner)),
    ]

    results = []
    for name, predict, attributions in models:
        for label, attribution_fn in [
            ("trace", attributions),
            ("reversed_control", reversed_attributions(attributions)),
        ]:
            metrics = evaluate_fidelity(predict, attribution_fn, test_examples)
            results.append({
                "model": name,
                "attribution": label,
                "n_explained": metrics["n_explained"],
                "comprehensiveness": round(metrics["comprehensiveness"], 4),
                "sufficiency": round(metrics["sufficiency"], 4),
            })

    RESULTS_DIR.mkdir(exist_ok=True)
    fields = ["model", "attribution", "n_explained", "comprehensiveness", "sufficiency"]
    csv_path = RESULTS_DIR / f"fidelity_{tag}.csv"
    with open(csv_path, "w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(results)

    md_path = RESULTS_DIR / f"fidelity_{tag}.md"
    lines = [
        f"# Explanation fidelity: {tag}",
        "",
        "Generated by `python scripts/run_fidelity.py` — do not edit by hand.",
        f"Dataset: `{pathlib.Path(data_path).name}`. Split seed 42, 30% test.",
        "Comprehensiveness: higher = the trace's top rule is load-bearing.",
        "Sufficiency: closer to 0 = the top rule alone reproduces the prediction.",
        "The reversed control must score worse on comprehensiveness than the trace.",
        "",
        "| Model | Attribution | n | Comprehensiveness | Sufficiency |",
        "|---|---|---|---|---|",
    ]
    for row in results:
        lines.append(
            f"| {row['model']} | {row['attribution']} | {row['n_explained']} "
            f"| {row['comprehensiveness']} | {row['sufficiency']} |"
        )
    md_path.write_text("\n".join(lines) + "\n")
    return results, csv_path, md_path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data")
    parser.add_argument("--synthetic", type=int, metavar="N")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--tag")
    parser.add_argument("--schema", choices=sorted(SCHEMAS), default="creditcard")
    args = parser.parse_args()

    if bool(args.data) == bool(args.synthetic):
        sys.exit("pass exactly one of --data or --synthetic N")

    if args.synthetic:
        if args.schema != "creditcard":
            sys.exit("--synthetic generates creditcard-schema data only")
        data_path = ffd.DATA_DIR / f"creditcard_synthetic_seed{args.seed}.csv"
        ffd.generate_synthetic(args.synthetic, args.seed, data_path)
        tag = args.tag or f"synthetic_n{args.synthetic}_seed{args.seed}"
        print("SYNTHETIC DATA — development results, not paper results.")
    else:
        data_path = args.data
        tag = args.tag or pathlib.Path(args.data).stem

    schema = SCHEMAS[args.schema]
    temporal = rx.TEMPORAL_SPLITS.get(args.schema)
    results, csv_path, md_path = run(data_path, tag, schema=schema, temporal=temporal)
    for row in results:
        print(row)
    print(f"written: {csv_path} and {md_path}")


if __name__ == "__main__":
    main()
